[workspace]
members = [
    "negentropy",
    "negentropy/fuzz/harness",
    "negentropy/fuzz/perf",
    "negentropy-ffi",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"